import os
from datetime import datetime

ACTION_PATH = r"D:\Routine_Digital_Assistant\vault\Needs_Action"
DRAFTS_PATH = r"D:\Routine_Digital_Assistant\vault\Drafts"

if __name__ == "__main__":
    if not os.path.exists(DRAFTS_PATH):
        os.makedirs(DRAFTS_PATH)
    
    actions = [f for f in os.listdir(ACTION_PATH) if f.startswith("ACTION_") and f.endswith(('.md', '.txt'))]
    print(f"Processing {len(actions)} actions...")
    
    for action in actions:
        try:
            file_path = os.path.join(ACTION_PATH, action)
            with open(file_path, "r", encoding="utf-8") as f:
                content = f.read()
            
            sender = "Unknown"
            subject = "No Subject"
            if "From:" in content:
                sender = content.split("From:")[1].split("\n")[0].strip()
            if "Subject:" in content:
                subject = content.split("Subject:")[1].split("\n")[0].strip()
            
            draft_name = f"DRAFT_{action}"
            draft_path = os.path.join(DRAFTS_PATH, draft_name)
            
            response = f"""# 📝 EXECUTIVE DRAFT: {subject}
**Target Recipient**: {sender}
**Account Context**: {action.split('_')[2] if 'tahiryamin' in action else 'Primary'}

---

## Proposed Response

Dear {sender},

I have received your communication regarding "{subject}". 

This is an automated acknowledgement generated by my Routine Digital Assistant. Your email has been flagged for my senior review, and I will be providing a detailed response shortly.

Best Regards,
Tahir Yamin
PMP | Senior Planning Engineer

---
*Generated by RDA Silver Tier | Awaiting Manual Approval*
"""
            with open(draft_path, "w", encoding="utf-8") as f:
                f.write(response)
            safe_subject = subject.encode('ascii', 'ignore').decode('ascii')
            print(f"SUCCESS: Draft created for: {safe_subject}")
        except Exception as e:
            print(f"ERROR processing {action}: {str(e).encode('ascii', 'ignore').decode('ascii')}")
